'use client'

import { useEffect, useState } from 'react'
import './globals.css'
import { UserLocationContext } from './context/UserLocationContext';

const metadata = {
  title: 'ByteForgeDev',
  description: 'Generated by ByteForgeDev',
}

export default function RootLayout({ children }) {

  const [userLocation, setUserLocation] = useState([]);

  useEffect(() => {
    getUserLocation()
  }, [])

  const getUserLocation = () => {
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log(pos)
      setUserLocation({
        lat: pos.coords.latitude,
        lng: pos.coords.longitude
      })
    })
  }

  return (
    <html lang="en">
      <body>
        <UserLocationContext.Provider value={{userLocation, setUserLocation}}>
          {children}
        </UserLocationContext.Provider>
      </body>
    </html>
  )
}
